# Generated by Django 6.0.5 on 2026-06-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movielist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('dname', models.CharField()),
                ('rating', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
